name: Twitter Analysis CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install unzip
        run: |
          sudo apt-get install unzip
      - name: Unzip the file
        run: |
          unzip ./data/Economic_Twitter_Data.zip

      - name: Test with pytest
        run: |
          name: Twitter Analysis CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install unzip
        run: |
          sudo apt-get install unzip
      - name: Unzip the file
        run: |
          unzip ./data/Economic_Twitter_Data.zip

      - name: Test data exctration
        run: |
          python -m unittest tests.test_extract_dataframe
      - name : Test clean tweet   
          python -m unittest tests.test_clean_tweets_dataframe
